steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/mystical-surfer-357409/todo-api:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/mystical-surfer-357409/todo-api:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  # args: ['run', 'deploy', 'SERVICE-NAME', '--image', 'gcr.io/PROJECT_ID/IMAGE', '--region', 'REGION']
  args:
   - 'run'
   - 'deploy'
   - 'todo-api'
   - '--image'
   - 'eu.gcr.io/mystical-surfer-357409/todo-api:$COMMIT_SHA'
   - '--region'
   - 'europe-west1'
images:
- eu.gcr.io/mystical-surfer-357409/todo-api:$COMMIT_SHA